name: ffi_libserialport
version: 0.0.1
author: Akos Belakovics <belakovics.akos@gmail.com>
description: >-
  A Dart interface to LibSerialPort through Dart FFI. This library wraps the
  experimental libserialport C API.
homepage: https://github.com/defned/ffi_libserialport

environment:
  sdk: '>=2.6.0-dev.6.0 <3.0.0'

dependencies:
  path: ^1.6.2
  quiver: ^2.0.3
  ffi: ^0.1.3-dev.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.6.4
